# Use the official ROS Noetic base image
FROM ros:noetic-ros-base-focal

WORKDIR /ros_ws

# Install rosbridge_server
RUN apt-get update && \
    apt-get install -y \
    ros-noetic-rosbridge-server \
    && rm -rf /var/lib/apt/lists/*

# Set up the environment
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc